language: node_js
node_js:
- 4.2.4
script:
- npm test
after_success:
- ./deploy.sh
env:
  global:
    secure: BE1XQShSrTFC2fKjU4lfW+t1qkehkgUCEGRuhwgIfgTPGCCasB74aDKR5BAWmuapl5agHBeZcUK8Lc37ypKtzpdoUCfEpqg8sR0lnf47V+5sRrNawwlMsGC461rQx+OzgHCgEPMCPyzJhYIKawUuLt8WMyBBDKhiC32vnW9w7F1TGx3qxyRETOWxaZFsvARj09WPD5DBxgmXeutc/N/gUvQM9QehfevN9i/WgBKolKYbnmPHmjqHysIw4eOUTlC5d+PkyGdFa6yUvugcyD82OTXdFJroAd6XpvsL57pl5kP1Hy89jG/gLnBIzE97yyBlVzDlhJGtV7V6TX34U+cVbpXn05wtLGseMktic3c8L/0tRoOxIqLZcPNgpW/D9pIlNL3LNPyEsiZw9FexRbSqc3eoH1S+JWV2MbsLEbZjwj91fOeGTlBWtzwjJaGKKqvHjECFeXdywiZsBRtgJESjJHo/khkpGx+RsX1wLnuiR8zzurrKzpu+L0cbeWWiPi0REQfa+5oB5tEtnYxnjb3uqXBKnvNKGUDYiGVSnrl9+Uvav86h8EDB1KH9Lq3yVK5EK6ncftkFKKlR8T8+Mt4gUMlnyeFDeRpB0p7ZAScC9ONYVNVmsYtCGNBM4jkE+lxaJLGisiyhJ/hFP32WlgDUS/v84wSxki3C3+4kdeKZKnk=
